# ISA 414 - Managing Big Data
## Lecture 5 - Preliminaries (Part IV): User-Defined Functions and Modules

#### Slide 5

In [7]:
# the command below calculates the sum of 1 + 1
1+1

2

#### Slide 6

In [8]:
1 + 1 # another comment

2

In [9]:
"""
A multi-line
comment
in Python
"""
print("See how everything above was ignored")

See how everything above was ignored

#### Slide 9

In [10]:
def RatioMaxMin(value_1, value_2):
    ratio = max(value_1, value_2) / min(value_1, value_2)
    return ratio

#### Slide 10

In [11]:
print(RatioMaxMin(10,2))
print(RatioMaxMin(2, 10))
print(RatioMaxMin(1,2))

5.0
5.0
2.0

In [12]:
# you will get an error
print(RatioMaxMin(10,0))

ZeroDivisionError: division by zero

In [ ]:
# you will get an error
print(RatioMaxMin(10,'0'))

#### Slide 11

In [ ]:
def RatioMaxMin2(value_1, value_2 = 10):
    ratio = max(value_1, value_2) / min(value_1, value_2)
    return ratio

#### Slide 12

In [ ]:
print(RatioMaxMin2(10))
print(RatioMaxMin2(5))
# 2 replaces 10
print(RatioMaxMin2(5,2))

1.0
2.0
2.5

#### Slide 13

In [ ]:
def RatioMaxMin3(value_1, value_2 = 10):
    if type(value_1) == int and type(value_2) == int:
        ratio = max(value_1, value_2) / min(value_1, value_2)
        return ratio
    else:
        return "One of the arguments is not of type integer"

In [ ]:
# testing the above function
print(RatioMaxMin3(10,2))
print(RatioMaxMin3(10,"2"))

5.0
One of the arguments is not of type integer

#### Slide 14

In [ ]:
def RatioMaxMin3(value_1, value_2 = 10):
    try:
        ratio = max(value_1, value_2) / min(value_1, value_2)
        return ratio
    except:
        return "An error occurred"

In [ ]:
# testing the above function
print(RatioMaxMin3(10,0))
print(RatioMaxMin3(10,"2"))
print(RatioMaxMin3(10.0,3.6))

An error occurred
An error occurred
2.7777777777777777

In [ ]:
def show_numbers(*numbers):
    for num in numbers:
        print(num)

In [ ]:
show_numbers(1,2,3)
show_numbers(1)

1
2
3
1

In [ ]:
def show_students_records(**students):
    print(students)

In [ ]:
show_students_records(student_name = 'Nick', grade = 90, student_name2 = 'Donnie', grade2 = 93)

{'student_name': 'Nick', 'grade': 90, 'student_name2': 'Donnie', 'grade2': 93}

In [ ]:
square = lambda x: x**2
print(square(5))

25

#### Slide 19

In [ ]:
# first code
import mymodule
mymodule.increment_by_two (10)

# forgot to save mymodule.py

ModuleNotFoundError: No module named 'mymodule'

In [ ]:
# second code
import mymodule as mm

mm.increment_by_two (10)

#### Slide 20

In [ ]:
from mymodule import my_var

my_var[1]

#### Slide 22

In [15]:
%pip install requests --upgrade

#%pip list
#%pip show pandas

Requirement already satisfied: requests in /opt/anaconda3/lib/python3.13/site-packages (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/anaconda3/lib/python3.13/site-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2023.5.7 in /opt/anaconda3/lib/python3.13/site-packages (from requests) (2025.8.3)
Note: you may need to restart the kernel to use updated packages.

#### Slide 26

In [16]:
%pip install folium

Requirement already satisfied: folium in /opt/anaconda3/lib/python3.13/site-packages (0.20.0)
Requirement already satisfied: branca>=0.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from folium) (0.8.2)
Requirement already satisfied: jinja2>=2.9 in /opt/anaconda3/lib/python3.13/site-packages (from folium) (3.1.6)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.13/site-packages (from folium) (2.1.3)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.13/site-packages (from folium) (2.34.2)
Requirement already satisfied: xyzservices in /opt/anaconda3/lib/python3.13/site-packages (from folium) (2022.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.13/site-packages (from jinja2>=2.9->folium) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests->folium) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests->folium) (3.7)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/anaconda3/lib/python3.13/site-packages (from requests->folium) (2.3.0)
Requirement already satisfied: certifi>=2023.5.7 in /opt/anaconda3/lib/python3.13/site-packages (from requests->folium) (2025.8.3)
Note: you may need to restart the kernel to use updated packages.

#### Slide 27

In [17]:
from folium import Map, Marker 
import pandas

/opt/anaconda3/lib/python3.13/site-packages/pandas/core/computation/expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

#### Slide 28

In [18]:
# reading the data
df = pandas.read_csv("web_log.csv")

df

          City        Client_IP   Country_Name   Latitude   Longitude
0    Singapore  128.199.234.236      Singapore   1.293100  103.855797
1    Singapore  128.199.234.236      Singapore   1.293100  103.855797
2    Singapore  128.199.234.236      Singapore   1.293100  103.855797
3    Singapore  128.199.234.236      Singapore   1.293100  103.855797
4    Singapore  128.199.234.236      Singapore   1.293100  103.855797
..         ...              ...            ...        ...         ...
994    Ashburn     54.227.93.32  United States  39.043701  -77.487503
995    Ashburn     54.227.93.32  United States  39.043701  -77.487503
996    Ashburn     54.227.93.32  United States  39.043701  -77.487503
997    Ashburn     54.227.93.32  United States  39.043701  -77.487503
998    Ashburn     54.227.93.32  United States  39.043701  -77.487503

[999 rows x 5 columns]

In [19]:
# removing rows that contain duplicate combinations of latitude and longitude
df = df.drop_duplicates(["Latitude","Longitude"])
df

              City        Client_IP    Country_Name   Latitude   Longitude
0        Singapore  128.199.234.236       Singapore   1.293100  103.855797
5    Mountain View    66.249.76.236   United States  37.386002 -122.083801
6          Guiyang    222.85.131.87           China  26.583300  106.716698
8         Shanghai  101.226.168.225           China  31.045601  121.399696
12       Zhengzhou   182.118.25.227           China  34.683601  113.532501
17       Hyderabad   122.175.18.128           India  17.375299   78.474403
24         Beijing     180.76.6.144           China  39.928902  116.388298
38        Shenzhen     202.46.62.17           China  22.533300  114.133301
39           Tokyo   119.63.193.130           Japan  35.685001  139.751404
46             NaN   37.188.237.170  Czech Republic  49.750000   15.500000
74       Guangzhou     59.42.126.21           China  23.116699  113.250000
77           Tracy  108.239.134.115   United States  37.737499 -121.425797
78             NaN      8.35.201.55   United States  38.000000  -97.000000
80         Ashburn     107.22.83.91   United States  39.043701  -77.487503
119            NaN   91.199.119.254          Israel  31.500000   34.750000
123      Charlotte    143.165.48.50   United States  35.227100  -80.843102
125        Raleigh      99.3.64.127   United States  35.848000  -78.700401
135    Camponogara     87.0.176.240           Italy  45.384998   12.072200
155        Bangkok      61.90.20.30        Thailand  13.754000  100.501404
761            NaN      46.27.28.87           Spain  40.000000   -4.000000

#### Slide 29

In [20]:
# Create a map centered at a specific location (adjust as needed)
m = Map(zoom_start=1)

# Add markers with names to the map
for index in range(len(df)):
    latitude = df.iloc[index,3]
    longitude = df.iloc[index,4]
    name = df.iloc[index,0]
    marker = Marker([latitude, longitude], popup=name)
    marker.add_to(m)

# Display the map
m

Saving the map to HTML

In [21]:
m.save("web_map.html")