# ISA 414 - Managing Big Data
## Lecture 5 - Preliminaries (Part IV): User-Defined Functions and Modules

#### Slide 5

In [1]:
# the command below calculates the sum of 1 + 1
1+1

2

#### Slide 6

In [2]:
1 + 1 # another comment

2

In [3]:
"""
A multi-line
comment
in Python
"""
print("See how everything above was ignored")

See how everything above was ignored

#### Slide 9

In [4]:
def RatioMaxMin(value_1, value_2):
    ratio = max(value_1, value_2) / min(value_1, value_2)
    return ratio

#### Slide 10

In [5]:
print(RatioMaxMin(10,2))
print(RatioMaxMin(2, 10))
print(RatioMaxMin(1,2))

5.0
5.0
2.0

#### Slide 11

In [6]:
def RatioMaxMin2(value_1, value_2 = 10):
    ratio = max(value_1, value_2) / min(value_1, value_2)
    return ratio

#### Slide 12

In [7]:
print(RatioMaxMin2(10))
print(RatioMaxMin2(5))
print(RatioMaxMin2(5,2))

1.0
2.0
2.5

#### Slide 13

In [8]:
def RatioMaxMin3(value_1, value_2 = 10):
    if type(value_1) == int and type(value_2) == int:
        ratio = max(value_1, value_2) / min(value_1, value_2)
        return ratio
    else:
        return "One of the arguments is not of type integer"

In [9]:
# testing the above function
print(RatioMaxMin3(10,2))
print(RatioMaxMin3(10,"2"))

5.0
One of the arguments is not of type integer

#### Slide 14

In [10]:
def RatioMaxMin3(value_1, value_2 = 10):
    try:
        ratio = max(value_1, value_2) / min(value_1, value_2)
        return ratio
    except:
        return "An error occurred"

In [11]:
# testing the above function
print(RatioMaxMin3(10,0))
print(RatioMaxMin3(10,"2"))

An error occurred
An error occurred

#### Slide 19

In [12]:
# first code
import mymodule

mymodule.increment_by_two (10)

12

In [13]:
# second code
import mymodule as mm

mm.increment_by_two (10)
mm.my_var

['ISA', 414]

#### Slide 20

In [14]:
from mymodule import my_var

my_var[1]

414

In [15]:
from mymodule import increment_by_two

increment_by_two(10)

12

#### Slide 22

In [16]:
# %pip install requests --upgrade

# %pip list
%pip show pandas

Name: pandas
Version: 2.3.3
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author:
Author-email: The Pandas Development Team <pandas-dev@python.org>
License: BSD 3-Clause License

 Copyright (c) 2008-2011, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team
 All rights reserved.

 Copyright (c) 2011-2023, Open source contributors.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

 * Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Location: c:\python\Lib\site-packages
Requires: numpy, python-dateutil, pytz, tzdata
Required-by: bokeh, datashader, holoviews, hvplot, panel, seaborn, statsmodels, streamlit, xarray
Note: you may need to restart the kernel to use updated packages.

#### Slide 26

In [17]:
%pip install folium

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: folium in c:\users\carothlj\appdata\roaming\python\python313\site-packages (0.20.0)
Requirement already satisfied: branca>=0.6.0 in c:\users\carothlj\appdata\roaming\python\python313\site-packages (from folium) (0.8.2)
Requirement already satisfied: jinja2>=2.9 in c:\python\lib\site-packages (from folium) (3.1.6)
Requirement already satisfied: numpy in c:\python\lib\site-packages (from folium) (2.3.5)
Requirement already satisfied: requests in c:\users\carothlj\appdata\roaming\python\python313\site-packages (from folium) (2.34.2)
Requirement already satisfied: xyzservices in c:\python\lib\site-packages (from folium) (2025.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\python\lib\site-packages (from jinja2>=2.9->folium) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\python\lib\site-packages (from requests->folium) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\python\lib\site-packages (from requests->folium) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in c:\python\lib\site-packages (from requests->folium) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\python\lib\site-packages (from requests->folium) (2025.11.12)
Note: you may need to restart the kernel to use updated packages.

#### Slide 27

In [18]:
from folium import Map, Marker 
import pandas

#### Slide 28

In [24]:
# reading the data
df = pandas.read_csv("web_log.csv")

df

          City        Client_IP   Country_Name   Latitude   Longitude
0    Singapore  128.199.234.236      Singapore   1.293100  103.855797
1    Singapore  128.199.234.236      Singapore   1.293100  103.855797
2    Singapore  128.199.234.236      Singapore   1.293100  103.855797
3    Singapore  128.199.234.236      Singapore   1.293100  103.855797
4    Singapore  128.199.234.236      Singapore   1.293100  103.855797
..         ...              ...            ...        ...         ...
994    Ashburn     54.227.93.32  United States  39.043701  -77.487503
995    Ashburn     54.227.93.32  United States  39.043701  -77.487503
996    Ashburn     54.227.93.32  United States  39.043701  -77.487503
997    Ashburn     54.227.93.32  United States  39.043701  -77.487503
998    Ashburn     54.227.93.32  United States  39.043701  -77.487503

[999 rows x 5 columns]

In [28]:
# removing rows that contain duplicate combinations of latitude and longitude
df = df.drop_duplicates(["Latitude","Longitude"])
df = df.dropna()
df

              City        Client_IP   Country_Name   Latitude   Longitude
0        Singapore  128.199.234.236      Singapore   1.293100  103.855797
5    Mountain View    66.249.76.236  United States  37.386002 -122.083801
6          Guiyang    222.85.131.87          China  26.583300  106.716698
8         Shanghai  101.226.168.225          China  31.045601  121.399696
12       Zhengzhou   182.118.25.227          China  34.683601  113.532501
17       Hyderabad   122.175.18.128          India  17.375299   78.474403
24         Beijing     180.76.6.144          China  39.928902  116.388298
38        Shenzhen     202.46.62.17          China  22.533300  114.133301
39           Tokyo   119.63.193.130          Japan  35.685001  139.751404
74       Guangzhou     59.42.126.21          China  23.116699  113.250000
77           Tracy  108.239.134.115  United States  37.737499 -121.425797
80         Ashburn     107.22.83.91  United States  39.043701  -77.487503
123      Charlotte    143.165.48.50  United States  35.227100  -80.843102
125        Raleigh      99.3.64.127  United States  35.848000  -78.700401
135    Camponogara     87.0.176.240          Italy  45.384998   12.072200
155        Bangkok      61.90.20.30       Thailand  13.754000  100.501404

#### Slide 29

In [29]:
# Create a map centered at a specific location (adjust as needed)
m = Map(zoom_start=1)

# Add markers with names to the map
for index in range(len(df)):
    latitude = df.iloc[index,3]
    longitude = df.iloc[index,4]
    name = df.iloc[index,0]
    marker = Marker([latitude, longitude], popup=name)
    marker.add_to(m)

# Display the map
m

Saving the map to HTML

In [ ]:
m.save("web_map.html")